settings:
  language: en_US
  version: 1 # recommended to not touch
  use-mysql: false # uses SQLite if false
  mysql: # use if 'use-mysql' is true
    host: localhost
    port: '3306'
    database: chatgames
    user: root
    password: ''


game:
  required-players: 1
  game-gap: 4 # in minutes must be greater than question length