settings:
  language: en_US
  version: 1 # recommended to not touch
  use-mysql: false # uses SQLite if false
  mysql: # ignore below if 'use-mysql' is false
    host: localhost
    port: '3306'
    database: chatgames
    user: root
    password: ''


game:
  required-players: 1
  show-players-message: false # should it show what the player typed in chat upon answering the question
  sound:
    name: ENTITY_CHICKEN_EGG # use 'none' for no sound
    pitch: 1
    volume: 0.5
  game-gap: 4 # in minutes must be greater than question length